upstream dists {
    server 10.0.2.20:80 weight=3; # dist1
    server 10.0.2.10:80 weight=1; # dist2
}

server { 
    listen 80;
    server_name www.distribuidos.net servicios.distribuidos.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.distribuidos.net;

    ssl_certificate /etc/nginx/ssl/distribuidos.crt;
    ssl_certificate_key /etc/nginx/ssl/distribuidos.key;
    
    location / {
        proxy_pass http://dists;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name servicios.distribuidos.net;

    ssl_certificate /etc/nginx/ssl/distribuidos.crt;
    ssl_certificate_key /etc/nginx/ssl/distribuidos.key;

    location / {
        proxy_pass http://dists;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}