version: '3.8'

x-common-config: &common-env
  AUTOR_API_URL: "http://autor-api:8082"
  EDITORIAL_API_URL: "http://editorial-api:8081"
  LIBRO_API_URL: "http://libro-api:8083"
  PYTHONPATH: "/app"

services:
  editorial-api:
    build: ./editorial
    command: python api/editorial.py
    container_name: serviceEditorial
    environment:
      <<: *common-env  
      DATA_PATH_EDITORIAL: "/app/database/editorial.json"
      PORT_EDITORIAL: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped

  autor-api:
    build: ./autor
    command: python api/autor.py
    container_name: serviceAutor
    environment:
      <<: *common-env 
      DATA_PATH_AUTOR: "/app/database/autor.json" 
      PORT_AUTOR: 8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    
  libro-api:
    build: ./libro
    command: python api/libro.py
    container_name: serviceLibro
    environment:
      <<: *common-env
      DATA_PATH_LIBRO: "/app/database/libro.json"
      PORT_LIBRO: 8083
    ports:
      - "8083:8083"
    restart: unless-stopped