# Definición de variables comunes (Mapa de la red interna)
x-common-config: &common-env
 
  AUTOR_API_URL: "http://autor-api:8082"
  DATA_PATH_AUTOR: "/app/data/autor.json"


  EDITORIAL_API_URL: "http://editorial-api:8081"
  DATA_PATH_EDITORIAL: "/app/data/editorial.json"

  LIBRO_API_URL: "http://libro-api:8083"
  DATA_PATH_LIBRO: "/app/data/libro.json"

  PYTHONPATH: "/app"

services:
  editorial-api:
    build: .
    command: python editorial/api/editorial.py
    environment:
      <<: *common-env
      PORT_EDITORIAL: 8081
    volumes:
      - "/var/www/html:/app/data" 
    ports:
      - "8081:8081"
    restart: always

  autor-api:
    build: .
    command: python autor/api/autor.py
    environment:
      <<: *common-env
      PORT_AUTOR: 8082
    volumes:
      - "/var/www/html:/app/data"
    ports:
      - "8082:8082"
    restart: always
    
  libro-api:
    build: .
    command: python libro/api/libro.py
    environment:
      <<: *common-env
      PORT_LIBRO: 8083
    volumes:
      - "/var/www/html:/app/data"
    ports:
      - "8083:8083"
    restart: always