upstream servicios_all {
    # dist1
    server 10.0.2.20:8081; # Editorial
    server 10.0.2.20:8082; # Autor
    server 10.0.2.20:8083; # Libro

    # dist2
    server 10.0.2.10:8081; # Editorial
    server 10.0.2.10:8082; # Autor
    server 10.0.2.10:8083; # Libro
}

upstream servicio_libro {
    server 10.0.2.20:8083; # dist1
    server 10.0.2.10:8083; # dist2
}

#-------------
server {
    listen 80;
    server_name www.distribuidos.net;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ @servicios;
    }

    location @servicios {
        proxy_pass http://servicios_all;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name servicios.distribuidos.net;

    location / {

        proxy_pass http://servicio_libro;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}