server {
    listen 80;
    server_name www.distribuidos.net servicios.distribuidos.net;
    
    # Redirige todo el tráfico HTTP al equivalente HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.distribuidos.net;

    ssl_certificate /etc/nginx/ssl/distribuidos.crt;
    ssl_certificate_key /etc/nginx/ssl/distribuidos.key;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/editorial {
        proxy_pass http://upstream_editorial;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https; # Avisa al backend que es seguro
    }

    location ~ ^/autor {
        proxy_pass http://upstream_autor;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location ~ ^/libro {
        proxy_pass http://upstream_libro;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name servicios.distribuidos.net;

    ssl_certificate /etc/nginx/ssl/distribuidos.crt;
    ssl_certificate_key /etc/nginx/ssl/distribuidos.key;

    location / {
        proxy_pass http://upstream_libro;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}