server {
    listen 80;
    server_name www.distribuidos.net;
    
    root /usr/share/nginx/html; 
    index index.html;
    server_tokens off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss;
    gzip_min_length 1000;

    location / {
        try_files $uri $uri/ =404;
        autoindex off;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

server {
    listen 80;
    server_name servicios.distribuidos.net;
    server_tokens off;

    default_type application/json;
    
    gzip on;
    gzip_types text/plain application/json;
    gzip_proxied any;
    gzip_min_length 1000;

    location ~ ^/editorial {
        proxy_pass http://editorial-api:8081;
    }

    location ~ ^/autor {
        proxy_pass http://autor-api:8082;
    }

    location ~ ^/libro {
        proxy_pass http://libro-api:8083;
    }

    error_page 500 502 503 504 /50x.json;
    location = /50x.json {
        return 502 '{"error": "502 Bad Gateway", "mensaje": "Microservicio offline"}';
    }
    
    error_page 404 /404.json;
    location = /404.json {
        return 404 '{"error": "404 Not Found", "mensaje": "Endpoint inválido"}';
    }
}